#!/bin/bash

#### jbosscheckticketgen.sh script
# This script checks whether the ticket has "template" files
# that are more recent than "generated" files. If this is the
# case, an error is raised to the user.
#
# Command line options:
#     TICKETNR		: The ticket number being checked
#     ENV		: The target environment
# Required files:
#     TI<ticketnr>-downloaded.txt: the downloaded.txt file as
#       generated by the handover tool.
# Constraints:
#     Only works on config or password tickets
#################################################################
# Change history
#################################################################
#      #             #
#      #             #
#      #             #
#      #             #
#################################################################
#

ScriptName="jbosscheckticketgen.sh"

DebugLevel=0
ArgTicketNr=$1
ArgOplEnv=$2

echo "Script" ${ScriptName}  "started."
echo "Options are:"
echo "  TICKETNR = '${ArgTicketNr}'"
echo "  OPL_ENV  = '${ArgOplEnv}'"


# Check the contents of the deleted and downloaded files
HandoverDeletedList="TI${ArgTicketNr}-deleted.txt"
HandoverDownloadedList="TI${ArgTicketNr}-downloaded.txt"

# Test 2: ensure downloaded.txt is NOT empty
if [ ! -s ${HandoverDownloadedList} ];
then
  echo "ERROR: Ticket contains no downloadable files, so there is nothing to deploy."
  exit 16
fi

# Under config there should be only 1 subfolder, which is typical for this ADC. Extract it.
line1=$(head -n 1 ${HandoverDownloadedList})
## expected format: OK      config/<adc-folder>/...
## remove the "OK" + tab section
line1=${line1:3}
firstpart=${line1%%"/"*}
restpart=${line1:${#firstpart}+1}
secondpart=${restpart%%"/"*}

## Enkel config en password tickets zijn van belang.
if [[ "$firstpart" != "config" ]] && [[ "$firstpart" != "password" ]]; then
  echo "Dit ticket gaat niet over config of password files. U kan verdergaan."
  exit 0
fi

TheOpl=$ArgOplEnv
SvnUsername="build-user"
SvnPassword="Argenta2000"
SvnOpts="--no-auth-cache --non-interactive --trust-server-cert --username ${SvnUsername} --password ${SvnPassword}"

svn ${SvnOpts} export https://scm/deployment/${TheOpl}/${firstpart}/${secondpart}/.handover/bom.txt

min_generated="9999-99-99 99:99:99"
max_template="0000-00-00 00:00:00"
while read colM fname id1 id2 id3 user sdate stime status rest
do
  syear=${sdate:6:4}
  smonth=${sdate:3:2}
  sday=${sdate:0:2}
  sfulldate="$syear-$smonth-$sday $stime"
  if [[ $fname == "generated/"* ]]; then
    if [[ $min_generated > $sfulldate ]]; then
      min_generated=$sfulldate
    fi
  fi
  if [[ $fname == "template/"* ]]; then
    if [[ $max_template < $sfulldate ]]; then
      max_template=$sfulldate
    fi
  fi
done < "bom.txt"

## bom.txt is nu niet meer nodig
rm bom.txt
## nu testen voor alle mogelijkheden van min_generated en van max_template

if [[ $max_template == "0000-00-00 00:00:00" ]]; then
  echo "Dit ticket heeft geen template files. U kan verdergaan."
  exit 0
fi
if [[ $min_generated == "9999-99-99 99:99:99" ]]; then
  echo "***********************************************************************"
  echo "***  FOUT   FOUT   FOUT   FOUT   FOUT   FOUT   FOUT   FOUT   FOUT   ***"
  echo "***********************************************************************"
  echo "Dit ticket heeft template files maar nog geen enkele gegenereerde file."
  echo "U moet eerst de files genereren via de daarvoor gepaste tool."
  echo "***********************************************************************"
  echo "***  FOUT   FOUT   FOUT   FOUT   FOUT   FOUT   FOUT   FOUT   FOUT   ***"
  echo "***********************************************************************"
  exit 16
fi

if [[ $min_generated < $max_template ]]; then
  echo "***********************************************************************"
  echo "***  FOUT   FOUT   FOUT   FOUT   FOUT   FOUT   FOUT   FOUT   FOUT   ***"
  echo "***********************************************************************"
  echo "    Dit ticket heeft template files en gegenereerde files."
  echo "    Maar sommige template files werden nog aangepast NADAT de"
  echo "            gegenereerde files werden aangemaakt."
  echo "    U moet eerst de files genereren via de daarvoor gepaste tool."
  echo "***********************************************************************"
  echo "***  FOUT   FOUT   FOUT   FOUT   FOUT   FOUT   FOUT   FOUT   FOUT   ***"
  echo "***********************************************************************"
  exit 16
fi

  echo "Dit ticket heeft gegenereerde files die recenter zijn dan de templates. U kan verdergaan."
  exit 0


echo "Script" ${ScriptName}  "ended."
